# Generated by Django 4.0.6 on 2022-07-14 05:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('ci', models.CharField(max_length=11, verbose_name='Carnet de identidad')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría científica')),
                ('cuenta_bancaria', models.CharField(max_length=16, verbose_name='Cuenta bancaria')),
                ('clasificador_entidad', models.CharField(max_length=10, verbose_name='Clasificar de entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('programa', models.CharField(max_length=100, verbose_name='Programa')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código del proyecto')),
                ('tipo', models.CharField(choices=[('n', 'Nacional'), ('s', 'Sectorial'), ('i', 'Institucional')], max_length=100, verbose_name='Tipo de proyecto')),
                ('area', models.CharField(max_length=100, verbose_name='Área administrativa')),
                ('resumen', models.CharField(max_length=500, verbose_name='Resumen del proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='RecursosHumanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, choices=[('1', 'Jefe de proyecto'), ('2', 'Profesor'), ('3', 'Estudiante'), ('4', 'Analista'), ('5', 'Desarrollador'), ('6', 'Gestor')], max_length=10, null=True, verbose_name='Cargo que ocupa')),
                ('institucion', models.CharField(choices=[('e', 'Empresa'), ('p', 'Presupuestado')], max_length=100, verbose_name='Institución')),
                ('porciento_de_participacion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='% de Participación')),
                ('salario_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario mensual')),
                ('salario_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario anual')),
                ('salario_externo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario externo')),
                ('porciento_de_remuneracion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='% de Remuneración')),
                ('mce', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MCE')),
                ('tiempo', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12)], verbose_name='Tiempo en meses')),
                ('anual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Anual')),
                ('salario_mensual_basico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario básico mensual')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.miembro')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='miembro',
            name='proyecto',
            field=models.ManyToManyField(through='core.RecursosHumanos', to='core.proyecto', verbose_name='Proyecto asociado'),
        ),
    ]
