# Generated by Django 4.0.6 on 2022-07-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='abreviacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Abreviación del nombre'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Logo del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del proyecto'),
        ),
    ]
