# Generated by Django 4.0.6 on 2022-07-20 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proyecto_abreviacion_proyecto_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='categoria_ocupacional',
            field=models.CharField(choices=[('C', 'Cuadro'), ('TI', 'Técnico de investigación'), ('OT', 'Otros técnicos'), ('O', 'Obreros'), ('S', 'Servicios')], max_length=100, verbose_name='Categoría ocupacional'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='ci',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Carnet de identidad'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='abreviacion',
            field=models.CharField(max_length=100, verbose_name='Abreviación del nombre'),
        ),
        migrations.AlterField(
            model_name='recursoshumanos',
            name='porciento_de_participacion',
            field=models.DecimalField(decimal_places=2, help_text='Debe ser menor que 100', max_digits=10, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Porciento de Participación'),
        ),
        migrations.AlterField(
            model_name='recursoshumanos',
            name='porciento_de_remuneracion',
            field=models.DecimalField(decimal_places=2, help_text='Debe ser menor que 100', max_digits=10, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Porciento de Remuneración'),
        ),
        migrations.AlterField(
            model_name='recursoshumanos',
            name='tiempo',
            field=models.PositiveSmallIntegerField(help_text='Debe ser menor que 12', validators=[django.core.validators.MaxValueValidator(12)], verbose_name='Tiempo en meses'),
        ),
    ]
